name = "ndr"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "129.150.58.86:57621"
UUID = "3dbf6f18-dd89-420a-8881-141e1c33c42d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
