name = "zzzhiar"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "178.128.80.43:443"
UUID = "d1b68fca-86c0-46fb-91df-947c6b1c0044"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
